### ISSUE TITLE
Landscape addition without zip

### ISSUE THREAD

**Issue by Elvie2** [Stellarium/stellarium-skycultures#18]
Would like to add older alt / az  text file with ini to a new version install which is looking for a zip file. This for astrophotography and an actual landscape would not be useful. Currently just have a polygon view / horizon and was hoping not to have to take photos. 

Is there a way to simply replicate the older methodology, or can I use my simple text file with an existing landscape?

Tx

**Comment by gzotti** [comment]
This is the repository for sky cultures, not for the program.
The method to add a 3rd-party made landscape via zip file has existed for many years now. However, the User Guide, chapter 7, describes the full process of creating your own landscape, be that polygonal or photographic.

**Comment by Elvie2** [comment]
Thanks Georg. Pardon my wrong choice of forum. First foray on the site. In the past I have added a landscape without the zip. I will review the manual.
